package com.example.coinnect

class CryptocurrencyProvider {
    companion object {
        val listaCryptos = mutableListOf<Cryptocurrency>(
            Cryptocurrency(
                "Bitcoin",
                "BTC",
                50000.0,
                "https://cdn.pixabay.com/photo/2021/04/30/16/47/bitcoin-logo-6219385_1280.png"
            ),
            Cryptocurrency(
                "Ethereum",
                "ETH",
                4000.0,
                "https://cdn.pixabay.com/photo/2021/05/24/09/15/ethereum-logo-6278329_1280.png"
            ),
            Cryptocurrency(
                "Ripple",
                "XRP",
                1.2,
                "https://cryptologos.cc/logos/xrp-xrp-logo.png"
            ),
            Cryptocurrency(
                "Litecoin",
                "LTC",
                150.0,
                "https://cryptologos.cc/logos/litecoin-ltc-logo.png"
            ),
            Cryptocurrency(
                "Cardano",
                "ADA",
                2.5,
                "https://cdn4.iconfinder.com/data/icons/crypto-currency-and-coin-2/256/cardano_ada-512.png"
            ),
            Cryptocurrency(
                "Polkadot",
                "DOT",
                30.0,
                "https://cryptologos.cc/logos/polkadot-new-dot-logo.png"
            ),
            Cryptocurrency(
                "Binance Coin",
                "BNB",
                400.0,
                "https://cryptologos.cc/logos/bnb-bnb-logo.png"
            ),
            Cryptocurrency(
                "Solana",
                "SOL",
                150.0,
                "https://cryptologos.cc/logos/solana-sol-logo.png"
            ),
            Cryptocurrency(
                "Dogecoin",
                "DOGE",
                0.25,
                "https://brandlogos.net/wp-content/uploads/2021/12/dogecoin-brandlogo.net_.png"
            ),
            Cryptocurrency(
                "Chainlink",
                "LINK",
                25.0,
                "https://cryptologos.cc/logos/chainlink-link-logo.png"
            ),
            Cryptocurrency(
                "Uniswap",
                "UNI",
                25.0,
                "https://cryptologos.cc/logos/uniswap-uni-logo.png"
            ),
            Cryptocurrency(
                "Avalanche",
                "AVAX",
                100.0,
                "https://cryptologos.cc/logos/avalanche-avax-logo.png"
            ),
            Cryptocurrency(
                "Terra",
                "LUNA",
                70.0,
                "https://img.freepik.com/vector-premium/terra-luna-token-nuevo-simbolo-cryptocurrency-logo-moneda-icono-aislado-sobre-fondo-blanco-ilustracion-vectorial_337410-1711.jpg"
            ),
            Cryptocurrency(
                "Polygon",
                "MATIC",
                2.0,
                "https://altcoinsbox.com/wp-content/uploads/2023/03/matic-logo.png"
            ),
            Cryptocurrency(
                "Shiba Inu",
                "SHIB",
                0.00005,
                "https://cdn3d.iconscout.com/3d/premium/thumb/shiba-inu-shib-coin-3d-icon-download-in-png-blend-fbx-gltf-file-formats--crypto-cryptocurrency-pack-science-technology-icons-6044464.png?f=webp"
            ),
            Cryptocurrency(
                "VeChain",
                "VET",
                0.15,
                "https://cryptologos.cc/logos/vechain-vet-logo.png"
            ),
            Cryptocurrency(
                "Tezos",
                "XTZ",
                5.0,
                "https://cryptologos.cc/logos/tezos-xtz-logo.png"
            ),
            Cryptocurrency(
                "Aave",
                "AAVE",
                400.0,
                "https://cryptologos.cc/logos/aave-aave-logo.png"
            ),
            Cryptocurrency(
                "SushiSwap",
                "SUSHI",
                15.0,
                "https://cryptologos.cc/logos/sushiswap-sushi-logo.png"
            ),
            Cryptocurrency(
                "Theta",
                "THETA",
                6.0,
                "https://s2.coinmarketcap.com/static/img/coins/200x200/2416.png"
            ),
            Cryptocurrency(
                "Cosmos",
                "ATOM",
                30.0,
                "https://cryptologos.cc/logos/cosmos-atom-logo.png"
            ),
            Cryptocurrency(
                "Filecoin",
                "FIL",
                80.0,
                "https://cryptologos.cc/logos/filecoin-fil-logo.png"
            ),
            Cryptocurrency(
                "Elrond",
                "EGLD",
                250.0,
                "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Elrond_Network_logo.svg/1200px-Elrond_Network_logo.svg.png"
            ),
            Cryptocurrency(
                "Zilliqa",
                "ZIL",
                0.1,
                "https://altcoinsbox.com/wp-content/uploads/2023/03/zilliqa-logo.png"
            ),
            Cryptocurrency(
                "Hedera Hashgraph",
                "HBAR",
                0.3,
                "https://cryptologos.cc/logos/hedera-hbar-logo.png"
            )
        )
    }
}
